# Generated by Django 4.2.16 on 2025-06-06 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('telephone', models.IntegerField()),
                ('recevoir_info', models.BooleanField(default=False)),
                ('pays', models.CharField(blank=True, max_length=200, null=True)),
                ('typeDon', models.CharField(blank=True, max_length=200, null=True)),
                ('information', models.CharField(max_length=250)),
            ],
        ),
    ]
