# Generated by Django 4.2.16 on 2025-06-06 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='recevoir_info',
            new_name='recevoirInfo',
        ),
    ]
