# Generated by Django 4.2.16 on 2025-06-13 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0002_rename_recevoir_info_information_recevoirinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='information',
        ),
    ]
