# Generated by Django 4.2.16 on 2025-06-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0003_remove_information_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='faireUnDon',
            field=models.BooleanField(default=False),
        ),
    ]
