# Generated by Django 4.2.16 on 2025-06-13 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0004_information_faireundon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='faireUnDon',
        ),
        migrations.RemoveField(
            model_name='information',
            name='pays',
        ),
        migrations.RemoveField(
            model_name='information',
            name='typeDon',
        ),
    ]
