# Generated by Django 4.2.16 on 2024-12-05 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_rename_courses_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books_title', models.CharField(max_length=50)),
                ('books_description', models.CharField(max_length=50)),
                ('books_image_name', models.CharField(max_length=50)),
                ('books_category', models.CharField(max_length=50)),
                ('book_link', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Books',
        ),
    ]
