# Generated by Django 4.2.16 on 2025-07-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='forum',
            field=models.BooleanField(default=False),
        ),
    ]
