# Generated by Django 4.2.16 on 2025-02-23 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_audio_passwordreset_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=20),
        ),
    ]
