# Generated by Django 4.2.16 on 2025-02-27 14:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_book_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='firstname',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='lastname',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='p_image',
            new_name='pImage',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='id',
        ),
        migrations.RemoveField(
            model_name='video',
            name='id',
        ),
        migrations.AddField(
            model_name='audio',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='video',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
