# Generated by Django 4.2.16 on 2025-03-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_rename_firstname_customuser_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='book',
            field=models.FileField(upload_to='books/file'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_cover',
            field=models.FileField(upload_to='books/book_cover'),
        ),
    ]
