# Generated by Django 4.2.16 on 2025-03-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_course_status_customuser_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='status',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phoneNumber',
        ),
        migrations.AddField(
            model_name='customuser',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
