# Generated by Django 4.2.16 on 2025-03-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_remove_course_status_remove_customuser_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='complete',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='open',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
