# Generated by Django 4.2.16 on 2025-03-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_lesson_complete_lesson_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='courseCover',
            field=models.FileField(default=1, upload_to='courses/courseCover'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='file',
            field=models.FileField(upload_to='courses/lessons'),
        ),
    ]
