# Generated by Django 4.2.16 on 2025-03-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_course_coursecover_alter_lesson_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courseCover',
            field=models.ImageField(upload_to='courses/courseCover'),
        ),
    ]
