# Generated by Django 4.2.16 on 2025-07-04 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_course_forum'),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='groupe_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='backend.course'),
        ),
    ]
