# Generated by Django 4.2.16 on 2025-07-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_remove_chatgroup_id_remove_groupmessage_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatgroup',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='groupmessage',
            name='uuid',
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
