# Generated by Django 4.2.16 on 2025-07-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_remove_chatgroup_uuid_remove_groupmessage_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='groupe_name',
            field=models.CharField(max_length=200),
        ),
    ]
