# Generated by Django 4.2.23 on 2025-07-03 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbs_blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='tags',
        ),
    ]
