# Generated by Django 4.2.16 on 2025-07-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbs_blogs', '0003_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
