# Generated by Django 4.2.16 on 2025-07-04 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbs_blogs', '0004_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(default=11, max_length=500),
            preserve_default=False,
        ),
    ]
