# Generated by Django 4.2.16 on 2025-01-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('teacher', 'TEACHER'), ('student', 'STUDENT'), ('admin', 'ADMIN')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
