# Generated by Django 4.2.16 on 2024-12-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books_title', models.CharField(max_length=50)),
                ('books_description', models.CharField(max_length=50)),
                ('books_image_name', models.CharField(max_length=50)),
                ('books_category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=50)),
                ('course_tutor', models.CharField(max_length=50)),
                ('course_description', models.CharField(max_length=50)),
            ],
        ),
    ]
