# Generated by Django 4.2.16 on 2024-12-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_student_teacher_rename_books_category_book_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='role',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
